### ISSUE TITLE
Where can I download pretrain/m2f_r50_coco.pth?

### ISSUE THREAD

**Issue by guikunchen** [king159/Pair-Net#3]
@king159 Thanks for your nice work!
I try the version released in [mmdet](https://download.openmmlab.com/mmdetection/v3.0/mask2former/mask2former_r50_8xb2-lsj-50e_coco-panoptic/mask2former_r50_8xb2-lsj-50e_coco-panoptic_20230118_125535-54df384a.pth), and it seems that the weights do not match:
2023-08-15 16:46:48,851 - mmdet - INFO - load checkpoint from local path: pretrain/m2f_r50_coco.pth
2023-08-15 16:46:49,597 - mmdet - WARNING - The model and loaded state dict do not match exactly
unexpected key in source state_dict: panoptic_head.pixel_decoder.input_convs.0.conv.weight, panoptic_head.pixel_decoder.input_convs.0.conv.bias, xxx (long sequence).

I guess this is the reason that testing results are all zero.

**Comment by nessie7purple** [comment]
Same problem. Could you please also provide the pretrained model?  @Jingkang50 @king159 
Thanks in advance !

**Comment by mingkaid** [comment]
Same problem here, looking forward to any clarification.

**Comment by Jingkang50** [comment]
@king159 Jinghao shall respond to this issue asap, this month?

**Comment by wyz-gitt** [comment]
Same problem here, looking forward to any clarification. I hope you can respond promptly, thank you very much.

**Comment by king159** [comment]
The pre-trained `Mask2Former` has been uploaded to `https://huggingface.co/king159/Pair-Net/tree/main`
